name: deployment-on-development-merge
run-name: 'Deployment on Development Merge: On Push'
on:
  push:
    branches:
      - development
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true
      - name: Run Build
        run: npm run build
  upload-asset:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - name: List files in dist
        run: ls -l
